version: '3.6'

services:
  zybooks-assignment-tracker:
    image: ghcr.io/phamleduy04/zybooks-assignment-tracker:alpine
    container_name: zybooks-assignment-tracker-bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      DATABASE_URL: etcd://zybooks-assignment-tracker-db:2379
    depends_on:
      - zybooks-assignment-tracker-db
  zybooks-assignment-tracker-db:
    image: docker.io/bitnami/etcd:3.4
    container_name: zybooks-assignment-tracker-db
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - link-grabber-bot-db:/bitnami/etcd
    restart: unless-stopped

volumes:
  zybooks-assignment-tracker-db:
    driver: local
